### ISSUE TITLE
Hi, you can use **_torch.save()_** to generate .pt file for your own few-shot samples.

### ISSUE THREAD

**Issue by kamenrideraway** [mala-lab/InCTRL#11]
Hi, you can use **_torch.save()_** to generate .pt file for your own few-shot samples.

_Originally posted by @Diana1026 in https://github.com/mala-lab/InCTRL/issues/7#issuecomment-2031421261_
            Thank you for this work.I want to test my own model,but I don't know exactly where should I use torch.save() to generate my own .pt file. And I don't know the structure of .pt file. Could you please give a more specific explaination? Thanks a lot.

**Comment by Diana1026** [comment]
Hi, you can write a script and save the image features after your own image transformation. The structure of image features should be 3x240x240 (aligned with the input of the visual encoder).

**Comment by kamenrideraway** [comment]
> Hi, you can write a script and save the image features after your own image transformation. The structure of image features should be 3x240x240 (aligned with the input of the visual encoder).

Thanks！
