### ISSUE TITLE
The performance of using 4-shot or 8-shot on the Visa dataset is similar to that of 2-shot

### ISSUE THREAD

**Issue by guangpintao** [mala-lab/InCTRL#12]
Hello, I validated the 8-shot performance using the provided pre-trained model and few shot samples, and the results were similar to 2-shot, not as high as mentioned in the paper. I did the following: (1) checkpoints/8/checkpoint.pyth modified TEST CHECKPOINT-FILE-PATH (2) changed/fs_samples/visa/2/in the provided test command to/fs_samples/visa/8/， results are as follows:
<img width="196" alt="image" src="https://github.com/mala-lab/InCTRL/assets/32570671/5138a9b0-4f4b-461e-ac23-f3d6dfd197cd">
Did I miss any operational steps？

**Comment by Qi-Ran** [comment]
您好，训练的命令时要一个类别一个类别的训练吗？

**Comment by REDriver2023** [comment]
> Hello, I validated the 8-shot performance using the provided pre-trained model and few shot samples, and the results were similar to 2-shot, not as high as mentioned in the paper. I did the following: (1) checkpoints/8/checkpoint.pyth modified TEST CHECKPOINT-FILE-PATH (2) changed/fs_samples/visa/2/in the provided test command to/fs_samples/visa/8/， results are as follows: <img alt="image" width="196" src="https://private-user-images.githubusercontent.com/32570671/323663758-5138a9b0-4f4b-461e-ac23-f3d6dfd197cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTM2NzAsIm5iZiI6MTcxMzc5MzM3MCwicGF0aCI6Ii8zMjU3MDY3MS8zMjM2NjM3NTgtNTEzOGE5YjAtNGY0Yi00NjFlLWFjMjMtZjNkNmRmZDE5N2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEzNDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYTRjYTBjNWJhZjU5NDUxZjY2ZWUyNzI1NzVkMmNiOTZiOGRiYjNkNWNiMTAzYzRmOTg2OWNlODE0Y2MyYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9vPertb7pXJXBKaMHri25DikygSLveWtJPVSCWSMrR0"> Did I miss any operational steps？

I also checked the performance on my device, my result is similar as stated in the paper. Here is my result:
<img width="301" alt="5ae17fadcd3a3619fa8016b31ef6a7c" src="https://github.com/mala-lab/InCTRL/assets/123659243/0bd8043c-8c79-4cbb-8a34-60a90a761870">
