### ISSUE TITLE
the training process

### ISSUE THREAD

**Issue by Qi-Ran** [mala-lab/InCTRL#14]
Hello, your paper has inspired me a lot, and I would like to reproduce the code. So, I would like to ask whether executing python main.py --normal_json_path $normal-json-files-for-training --outlier_json_path $abnormal-json-files-for-training --val_normal_json_path $normal-json-files-for-testing --val_outlier_json_path $abnormal-json-files-for-testing during the training process requires running one JSON file for each category in each dataset?

**Comment by Diana1026** [comment]
when training or testing on multiple datasets, you can concatenate the selected JSON files by adding a space between them.
