### ISSUE TITLE
Is the model trained on the full dataset of MVTec available?

### ISSUE THREAD

**Issue by gaobb** [mala-lab/InCTRL#16]
I understand that the [available model](https://drive.google.com/file/d/1zEHsbbuUgBC4yuDu3g23wbUGmWmVyDRQ/view?usp=sharing) is pre-trained on MVTec. Could you make your model pre-trained on the full dataset of ViSA available?

Best Regards,

**Comment by Diana1026** [comment]
Hi, please access the link again to view the models trained on the Visa. Thank you.
