### ISSUE TITLE
Few-shot Normal Images for Inference. 

### ISSUE THREAD

**Issue by CHELSEA234** [mala-lab/InCTRL#17]
@Diana1026
Many thanks for your awesome work. I am currently following the abnormal detection protocol you defined.

However, per the [public link](https://drive.google.com/drive/folders/1_RvmTqiCc4ZGa-Oq-uF7SOVotE1RW5QZ) on your GitHub page, it seems like you only released .pt files for few-shot normal samples, which do not have information (e.g., image names) to show which specific samples from each dataset were used to create these .pt files. In addition, the few-shot normal sample folder might not show .pt files for all $9$ datasets reported in your work. I would greatly appreciate it if you could share names of these few-shot samples used in the inference. 

I was trying to contact you via email, but my Outlook email app says jwzhu2022@phdcs.smu.edu.sg is not a valid email address.

**Comment by CHELSEA234** [comment]
@Diana1026 
May I ask if you happen to be at CVPR this year?

**Comment by Diana1026** [comment]
Hi, my email is jwzhu.2022@phdcs.smu.edu.sg. Sorry I have been working on another project recently, I will process the few-shot image name and release it soon, thanks for your patience.

**Comment by fpgboy** [comment]
> Hi, my email is [jwzhu.2022@phdcs.smu.edu.sg](mailto:jwzhu.2022@phdcs.smu.edu.sg). Sorry I have been working on another project recently, I will process the few-shot image name and release it soon, thanks for your patience.

Thank you for your previous work, too. Have you sorted them out now？

**Comment by Kerio99** [comment]
meet the same problem~

**Comment by Kerio99** [comment]
> @Diana1026 Many thanks for your awesome work. I am currently following the abnormal detection protocol you defined.
> 
> However, per the [public link](https://drive.google.com/drive/folders/1_RvmTqiCc4ZGa-Oq-uF7SOVotE1RW5QZ) on your GitHub page, it seems like you only released .pt files for few-shot normal samples, which do not have information (e.g., image names) to show which specific samples from each dataset were used to create these .pt files. In addition, the few-shot normal sample folder might not show .pt files for all 9 datasets reported in your work. I would greatly appreciate it if you could share names of these few-shot samples used in the inference.
> 
> I was trying to contact you via email, but my Outlook email app says [jwzhu2022@phdcs.smu.edu.sg](mailto:jwzhu2022@phdcs.smu.edu.sg) is not a valid email address.

Hi, have you solved this question?
