### ISSUE TITLE
After I use the convert_visa.py to convert Visa, I found that I can't generate the json file through the gen_train_json.py, could you have a check at the convert_visa.py? thanks a lot

### ISSUE THREAD

**Issue by cryingdxy** [mala-lab/InCTRL#2]

**Comment by Diana1026** [comment]
Hi, I've updated the convert_visa.py and you can follow the README file in preprocess to generate the json files.

**Comment by cryingdxy** [comment]
> Hi, I've updated the convert_visa.py and you can follow the README file in preprocess to generate the json files.

I found the README file noted that the dataset should be converted to MVTec_AD format, but this updated convert_visa.py still seems incorrect.
![image](https://github.com/mala-lab/InCTRL/assets/117656397/34364dd1-e804-47cc-8eef-28ba33a12a0b)
![image](https://github.com/mala-lab/InCTRL/assets/117656397/19d3f16e-0f91-4e87-a96c-3ccc4e13bc32)

**Comment by Diana1026** [comment]
Hello, your organization of files seems no problem. The train and test files are inside the sub-categories (e.g. candle).
![1](https://github.com/mala-lab/InCTRL/assets/87057339/4368be29-5b9a-4950-b392-157a029ea3c4)

**Comment by cryingdxy** [comment]
> Hello, your organization of files seems no problem. The train and test files are inside the sub-categories (e.g. candle). ![1](https://private-user-images.githubusercontent.com/87057339/315350034-4368be29-5b9a-4950-b392-157a029ea3c4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzMxODgsIm5iZiI6MTcxMTAzMjg4OCwicGF0aCI6Ii84NzA1NzMzOS8zMTUzNTAwMzQtNDM2OGJlMjktNWI5YS00OTUwLWIzOTItMTU3YTAyOWVhM2M0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0NTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNzA4MDY3OWQwYmY2NTE2ZTY2YTA4MmIwYThjOTIxMWRkOTY3MTU1YTM1ZmUwYTg3MDcxOTI2OWYwZTZhNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jZ6sgZ1RVJ8h57pEvHvLWRgF2ZKzxaEarXkCSCcSTzY)

I'm so sorry that I misunderstood your purpose. It is now running normally. Thank you very much!!!
