### ISSUE TITLE
Is it possible to not pass in the --few_shot_dir parameter during testing?

### ISSUE THREAD

**Issue by czy5638222** [mala-lab/InCTRL#20]
Is it possible to not pass in the --few_shot_dir parameter during testing?
If it is possible to not pass it in, what are the implications?

**Comment by Diana1026** [comment]
Hi, the parameter --few_shot_dir is the address saving the visual prompts. If you change the way to obtain visual prompts, you can remove it. But in our implementation, it is necessary.
