### ISSUE TITLE
json generation fails 

### ISSUE THREAD

**Issue by unit-0002** [mala-lab/InCTRL#22]
Dear InCTRL-Team @GuansongPang @Diana1026,

I wanted to set up your project on my own machine but bumped into an error.
When using your command in the Terminal
`python gen_val_json.py --dataset_root=./visa_anomaly_detection/visa --dataset_name=candle `
It says that the argument is not found. Quick look into the code and there is no dataset_name argument there.
What is the fix to my problem?

Best regards

**Comment by Diana1026** [comment]
Hi, the --dataset_name is in lines 12-13 of gen_val_json.py, please check it.

**Comment by baraa-m** [comment]
> Dear InCTRL-Team @GuansongPang @Diana1026,
> 
> I wanted to set up your project on my own machine but bumped into an error. When using your command in the Terminal `python gen_val_json.py --dataset_root=./visa_anomaly_detection/visa --dataset_name=candle ` It says that the argument is not found. Quick look into the code and there is no dataset_name argument there. What is the fix to my problem?
> 
> Best regards

For me I had to change --dataset_root  and use  --dataset_dir instead.

**Comment by unit-0002** [comment]
When I change it to --data_dir it throws an error:
`FileNotFoundErrpr: [Errno 2] No such file or directory: './datasets/AD_json/candle_val_normal.json`

What should i do next? @baraa-m

**Comment by Diana1026** [comment]
> > Dear InCTRL-Team @GuansongPang @Diana1026,
> > I wanted to set up your project on my own machine but bumped into an error. When using your command in the Terminal `python gen_val_json.py --dataset_root=./visa_anomaly_detection/visa --dataset_name=candle ` It says that the argument is not found. Quick look into the code and there is no dataset_name argument there. What is the fix to my problem?
> > Best regards
> 
> For me I had to change --dataset_root and use --dataset_dir instead.

Yes, thank you for your reminder. I have fixed the command.

**Comment by baraa-m** [comment]
> > > Dear InCTRL-Team @GuansongPang @Diana1026,
> > > I wanted to set up your project on my own machine but bumped into an error. When using your command in the Terminal `python gen_val_json.py --dataset_root=./visa_anomaly_detection/visa --dataset_name=candle ` It says that the argument is not found. Quick look into the code and there is no dataset_name argument there. What is the fix to my problem?
> > > Best regards
> > 
> > 
> > For me I had to change --dataset_root and use --dataset_dir instead.
> 
> Yes, thank you for your reminder. I have fixed the command.

@Diana1026 You are welcome :) I hope you can answer my question about : how to test your model on one image , i tried different methods but I was unable to do it :(

**Comment by baraa-m** [comment]
> When I change it to --data_dir it throws an error: `FileNotFoundErrpr: [Errno 2] No such file or directory: './datasets/AD_json/candle_val_normal.json`
> 
> What should i do next? @baraa-m

If it's not the case, you have to execute : 
python convert_visa.py --dataset_root=./AD_json/visa
before doing: 
python gen_val_json.py --dataset_dir=./visa_anomaly_detection/visa --dataset_name=candle 

You can also add the argument --output_dir to choose where to generate the json file
