### ISSUE TITLE
Few-shot Normal Samples for Inference - MVTec

### ISSUE THREAD

**Issue by Se0ngYe0l** [mala-lab/InCTRL#24]
I trained model using the Visa dataset and would like to check the results using the Mvtec dataset.

However, the Google Drive link provided for inference only has 6 types of datasets and the mvtec dataset does not exist.
(https://drive.google.com/drive/folders/1_RvmTqiCc4ZGa-Oq-uF7SOVotE1RW5QZ)

As a result of searching, I was able to find the few shot settings of the mvtec dataset in the link https://github.com/MediaBrain-SJTU/RegAD?tab=readme-ov-file

If you did not use the dataset from the link, can you share the dataset you used?

**Comment by Kerio99** [comment]
meet the same problem~

**Comment by Kerio99** [comment]
> I trained model using the Visa dataset and would like to check the results using the Mvtec dataset.
> 
> However, the Google Drive link provided for inference only has 6 types of datasets and the mvtec dataset does not exist. (https://drive.google.com/drive/folders/1_RvmTqiCc4ZGa-Oq-uF7SOVotE1RW5QZ)
> 
> As a result of searching, I was able to find the few shot settings of the mvtec dataset in the link https://github.com/MediaBrain-SJTU/RegAD?tab=readme-ov-file
> 
> If you did not use the dataset from the link, can you share the dataset you used?

Hi, have you solved this question?

**Comment by Diana1026** [comment]
Hi, please check the provided link again to view the few-shot samples used in mvtecad.
