### ISSUE TITLE
About performance on BrainMRI, HeadCT & AITEX datasets

### ISSUE THREAD

**Issue by Mouthhan** [mala-lab/InCTRL#29]
Hi, thanks for your excellent work, 
I edit my test batchsize to 1 and inference on BrainMRI, HeadCT & AITEX datasets.
I use the pretrained weights and randomly selected 8-shot normal prompts for inference, but my results seems significantly beyond the range of variation.

8-shot 
- AITEX : AUROC = 0.7363 / AUPRC = 0.3857
- BrainMRI : AUROC = 0.7997 / AUPRC = 0.9198
- HeadCT : AUROC = 0.8960 / AUPRC = 0.9711

Is there something important missing? or should I edit the transform for Medical images? @Diana1026

**Comment by Diana1026** [comment]
Hi, selecting different few-shot samples will influence the performance as the selected normal samples might not be a good representative of the normal pattern, we clarify the problem in Sec 4.4 Failure Cases of our paper, which is also the limitation of few-shot methods. You can try different samples.

We provided the support set files selected for these datasets in the given link.
