### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'vit_b_16_plus_240-laion400m_e32-699c4b84.pt'

### ISSUE THREAD

**Issue by hanli6688** [mala-lab/InCTRL#30]
where can i find this file?
i can't run the test.py or main.py.

**Comment by yoho131** [comment]
If you are using an Ubuntu system, it might be located here: /home/user/.cache/clip.
Just copy it to the InCTRL-main directory. (At least that's how it worked for me.)

**Comment by hanli6688** [comment]
thank you，but I am windows

**Comment by hanli6688** [comment]
> If you are using an Ubuntu system, it might be located here: /home/user/.cache/clip. Just copy it to the InCTRL-main directory. (At least that's how it worked for me.)

so do you know how to use it on windows

**Comment by Diana1026** [comment]
Hi, you can download it by [this link](https://github.com/mlfoundations/open_clip/releases/download/v0.2-weights/vit_b_16_plus_240-laion400m_e32-699c4b84.pt).
