### ISSUE TITLE
about gen_train_json.py file

### ISSUE THREAD

**Issue by yllGM** [mala-lab/InCTRL#31]
I want to know that whether the selected classes is missing JPG classes, and I thint it may cause the problems that missing data
![Uploading 240925.png…]()

**Comment by yllGM** [comment]
![Screenshot_20240926_003950.jpg](https://github.com/user-attachments/assets/ef4649c6-6314-4236-b508-8f32936f899e)
this part

**Comment by Diana1026** [comment]
Hi, if the 'JPG' images are not included in the dataset, then there should be no impact. You can also modify the code based on your requirements.
