### ISSUE TITLE
how to get the '.pt' of other datasets in the inference

### ISSUE THREAD

**Issue by zhanfengdog** [mala-lab/InCTRL#32]
how can I use the '.pt' of other datasets in the inference instead of 'visA' or 'Mvtecad'? 
It seems that I can't get the '.pt' file when training.
Thanks a lot for your help

**Comment by Diana1026** [comment]
Hi, I've provided support set files for other datasets in the given link. You can also write a script to randomly select the few-shot samples from the training set and save the image features after the image transformation. The dimensions of image features should be aligned with the input of the visual encoder.
