### ISSUE TITLE
About the parameters of the JSON file generation script.

### ISSUE THREAD

**Issue by GuoZX1999** [mala-lab/InCTRL#33]
Hello. I noticed when using the script to generate JSON files that there is no code to create a corresponding folder structure for the JSON files. The default output_dir parameter saves all JSON files in the same directory. Should I modify the output_dir parameter?

**Comment by GuoZX1999** [comment]
I cannot comprehend the meaning represented by "subset_1" in the JSON folder format. This is because in the corresponding VisA dataset, there are multiple categories of items, whereas in BrainMRI, there is only one category: "brainmri". When configuring the JSON file generation script for the VisA dataset, if the parameter "dataset_name" is set to values like "candle" and "capsules", would it suffice to have only "brainmri" as "subset_1" in BrainMRI?

**Comment by Diana1026** [comment]
Hi, for datasets that contain only one category (e.g., BrainMRI), they only have one subset (e.g., 'brainmri'), which is also the value of "dataset_name".
