### ISSUE TITLE
Problem on reproducing the result on Mvtec-capsule 

### ISSUE THREAD

**Issue by KarolineZhy** [mala-lab/InCTRL#34]
Dear author，
Thanks for your great work! 
I notice you upload the normal prompts for MVTec dataset. However, after using test batchsize=1 and change the pretrained model path, I get a very low value for the capsule class in mvtec dataset.
Here is the setting with num_shots=2:
![image](https://github.com/user-attachments/assets/51340fdf-b2cd-4fef-b899-832521c55b0a)

Here is the evaluation result:
![image](https://github.com/user-attachments/assets/93a0ab11-8006-46f2-bd86-ea14d909b501)

I notice most of the result is similar to the paper, but the result of capsule is far too low as written in the paper (86% in the paper). Is it because of the prompt? Since here you only give one prompt, but in the paper, you do several tests and get the mean and std. **Can I understand it as: the result will be sensitive to the choice of the normal prompts?**

Looking forward to your reply.

**Comment by Diana1026** [comment]
Hi, yes, selecting different few-shot samples will influence the performance as the selected normal samples might not be a good representative of the normal pattern, we clarify the problem in Sec 4.4 Failure Cases of our paper, which is also the limitation of few-shot methods.

**Comment by KarolineZhy** [comment]
Thanks for your reply!
