### ISSUE TITLE
lower performance for Visa dataset validation

### ISSUE THREAD

**Issue by Shmily-YH** [mala-lab/InCTRL#5]
hello, i download the provided model and few-shot normal samples as you said in Readme, and i just test the candle datas from visa testset with 2 shot, and the tesetset is spilit by "1cls.csv", the result i get is AUC-ROC: 0.8773, AUC-PR: 0.8693; it's obviously lower than the results describled in paper: AUROC-0.916, AUPRC: 0.920.

I can not find out where the problem is, so could you give me some suggesionts for check?

**Comment by Diana1026** [comment]
Could you please check if your pre-trained model and few-shot samples are correct? I downloaded the repository and tested the model again, and there was no problem. In addition, the test data statistics are provided in the Appendix and you can check your annotation JSON files based on it.

**Comment by Shmily-YH** [comment]
thanks for your reply! 

I added the pre-trained model path in _C.TEST_CHECKPOINT_FILE_PATH, and the run command is: python test.py --val_normal_json_path ../../visa/camdle_val_normal.json --val_outlier_json_path ../../visa/candle_val_outlier.json --category candle --few_shot_dir ../../visa/2

i checked the annotation json files, 100 normal images, 100 defect images, it seems everything is ok... 0.0

**Comment by wyxogo** [comment]
I also got lower performance (for visa candle, AUC-ROC: 0.8850, AUC-PR: 0.8706), about three points lower than the paper(AUPOC: 0.916±0.006, AUPRC: 0.920±0.008)

**Comment by Diana1026** [comment]
Hi, I downloaded the project and run directly, below is my current reproduced result:
<img width="996" alt="image" src="https://github.com/mala-lab/InCTRL/assets/87057339/69cabc8a-5ab7-49a1-a862-c1c2f9d8b56e">

**Comment by Diana1026** [comment]
Since our report's results are based on averages across various independent runs, there might be some deviation. I will release another few-shot sample set for selection later. However, for the current few-shot file, the results should be like the given image.

**Comment by AlperDiktas** [comment]
hi,
I download the visa and trained first, then tested. Reasults are really good.

![image](https://github.com/mala-lab/InCTRL/assets/87566696/0b2e1ba7-fdea-4a16-a52f-1d062bdd347a)

**Comment by guangpintao** [comment]
Same lower reproduction twice @Diana1026,  please check the few-shot sample set for selection. BTW, is the performance high affected  by few-shot sample?
<img width="251" alt="image" src="https://github.com/mala-lab/InCTRL/assets/32570671/a95839cb-ff9f-48e7-957c-1b2fc5673048">

**Comment by guangpintao** [comment]
> Same lower reproduction twice @Diana1026, please check the few-shot sample set for selection. BTW, is the performance high affected by few-shot sample? <img alt="image" width="251" src="https://private-user-images.githubusercontent.com/32570671/320271374-a95839cb-ff9f-48e7-957c-1b2fc5673048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODM3NTYsIm5iZiI6MTcxMjQ4MzQ1NiwicGF0aCI6Ii8zMjU3MDY3MS8zMjAyNzEzNzQtYTk1ODM5Y2ItZmY5Zi00OGU3LTk1N2MtMWIyZmM1NjczMDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5NTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMmZjODJiOTUyOWI4YjMwNzU4YjI4NTA1Yzg0NmU2NDU2YzhkOTQ3ZjhmZWU5MzU0MDhlYjU2MTY1MTQ1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ls3deARaflJXUPpJK17KAh5UnLcZ6riRbCMkQIuWe60">

<img width="1495" alt="image" src="https://github.com/mala-lab/InCTRL/assets/32570671/28132637-539d-47a7-95ec-ce78939057b4">
Result of capsules is good.

**Comment by Diana1026** [comment]
The results shouldn't change when the parameters(pre-trained model) and few-shot samples are fixed, and this is the reason why you got the same results twice. I used the same few-shot samples but the performance is the same as the image I uploaded. Please check if the hardware and the PyTorch version are aligned with us. 

Indeed, selecting different few-shot samples will influence the performance as the selected normal samples might not be a good representative of the normal pattern, we clarify the problem in Sec 4.4 Failure Cases of our paper.

**Comment by ximitiejiang** [comment]
for shot=2 and candle dataset, i got AUC_ROC=08027, AUC_PR=0.8096, with default setting.
and i tried to set batchsize from bs=8 to bs=2, then the performance raised to below
![image](https://github.com/mala-lab/InCTRL/assets/24242483/ced6c3cd-c286-4d73-9243-d0c6876d3002)

**Comment by gaobb** [comment]
lower performance for 2-shot candle class of ViSA

![image](https://github.com/mala-lab/InCTRL/assets/9379079/e99c750e-b486-4846-a0b8-f94cdc6b62b1)

**Comment by Diana1026** [comment]
Hi @guangpintao @ximitiejiang @Shmily-YH @wyxogo Please change the value of "_C.TEST.BATCH_SIZE" in open_clip/config/defaults.py to "1". In this case, the performance will be the same as mine. There might be a bug when the test batch size is larger than 1, and I am checking the code. Thank you.

**Comment by guangpintao** [comment]
Thanks for your reply, I will try it soon.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月3日(星期二) 晚上8:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mala-lab/InCTRL] lower performance for Visa dataset validation (Issue #5)














 
Hi @guangpintao @ximitiejiang @Shmily-YH @wyxogo Please change the value of "_C.TEST.BATCH_SIZE" in open_clip/config/defaults.py to "1". In this case, the performance will be the same as mine. There might be a bug when the test batch size is larger than 1, and I am checking the code. Thank you.
