### ISSUE TITLE
Can you provide the download address for vit'b_16_plus_240 laion400m_e32-699c4b84.pt

### ISSUE THREAD

**Issue by USTCXSC** [mala-lab/InCTRL#6]
Can you provide the download address for vit'b_16_plus_240 laion400m_e32-699c4b84.pt

**Comment by hejinsome** [comment]
you need to modify engine_IC.py:
    with pathmgr.open("./pretained/checkpoints/2/checkpoint.pyth", "rb") as f:
        checkpoint = torch.load(f, map_location="cpu")
run...

**Comment by Diana1026** [comment]
Hi, you can download it by [this link](https://github.com/mlfoundations/open_clip/releases/download/v0.2-weights/vit_b_16_plus_240-laion400m_e32-699c4b84.pt).
