### ISSUE TITLE
Can you provide code for visual inspection

### ISSUE THREAD

**Issue by czr1030** [mala-lab/InCTRL#8]
Thank you for your work. Can you provide the code for visual detection

**Comment by Diana1026** [comment]
Hello, may I know what the "visual detection" means?

**Comment by czr1030** [comment]
> Hello, may I know what the "visual detection" means?

Generate a heatmap of abnormal locations

**Comment by Diana1026** [comment]
In our paper, after obtaining the holistic in-context residual map M, we use **_sns.heatmap(M, linewidth=0.5, vmin=0, vmax=1, cmap="YlGnBu")_** to generate the heatmap. By the way, this heatmap is not intended for the anomaly segmentation task, which is not involved in InCTRL.
